### ISSUE TITLE
Errors Windows

### ISSUE THREAD

**Issue by ImInTheICU** [IsEmil/ironbrew-bot#7]
```
Logged In
ReferenceError: proccess is not defined
    at deployCommands (C:\Users\14794\Downloads\ironbrew-bot\index.js:65:62)
    at C:\Users\14794\Downloads\ironbrew-bot\index.js:111:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Client Ready
^C
```
Halp!

**Comment by IsEmil** [comment]
[LocalSmail](https://github.com/LocalSmail):
You need to do `npm install`
If it asks you to do `npm fund` or `npm audit fix --force` then do such and then try again.
