### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RatinhoFivem** [IsEmil/ironbrew-bot#8]
ReferenceError: proccess is not defined
    at deployCommands (C:\Users\CorinthiansMinhaVida\Desktop\ironbrew-bot-main\index.js:65:62)
    at C:\Users\CorinthiansMinhaVida\Desktop\ironbrew-bot-main\index.js:111:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Client Ready

**Comment by LocalSmail** [comment]
You need to do `npm install`

**Comment by LocalSmail** [comment]
If it asks you to do `npm fund` or `npm audit fix --force` then do such and then try again.
